name: Update Sheet Manually
on: workflow_dispatch

env:
  CYPRESS_LAMBDA_API_URL: ${{ secrets.CYPRESS_LAMBDA_API_URL }}
  CYPRESS_S3_BUCKET_URL: ${{ secrets.CYPRESS_S3_BUCKET_URL }}

jobs:
  create-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Write the cypress.env.json file 📝
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: yarn fixture
        run: |
          yarn fixture
      - name: yarn clear
        run: |
          yarn clear
      - uses: actions/upload-artifact@main
        with:
          name: fixtures
          path: cypress/fixtures
      - uses: actions/upload-artifact@main
        with:
          name: specs
          path: cypress/e2e

  cypress-run:
    runs-on: ubuntu-latest
    needs: create-fixtures
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Write the cypress.env.json file 📝
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - uses: actions/download-artifact@main
        with:
          name: fixtures
          path: cypress/fixtures
      - uses: actions/download-artifact@main
        with:
          name: specs
          path: cypress/e2e
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: Validate test filename
        id: validator
        shell: bash
        run: |
          if [ "$(node cypress-partial.js 50 ${{ matrix.containers }})" == "" ]; then
            echo ::set-output name=should-run::false
          else
            echo ::set-output name=should-run::true
          fi
      - name: Get result
        run: echo "${{steps.validator.outputs.should-run}}"
      - name: Cypress run
        if: ${{ steps.validator.outputs.should-run == 'true' }}
        run: |
          yarn start --spec $(node cypress-partial.js 50 ${{ matrix.containers }})

  delete-artifacts:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: ${{ always() }}
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            fixtures
            specs
